/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beta;

import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class AdminHome extends javax.swing.JFrame {

    
    
    public AdminHome() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminManageBookPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        AdminConcertsLabel = new javax.swing.JPanel();
        AdminCustomerLabel = new javax.swing.JLabel();
        ManageConcertsLabel = new javax.swing.JLabel();
        AdminBookingsLabel = new javax.swing.JLabel();
        AdminInvoiceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LoginInfoLabel = new javax.swing.JLabel();
        GeneralLoginPicLabel = new javax.swing.JLabel();
        GeneralLogOutLabel = new javax.swing.JLabel();
        AdminBotPanel = new javax.swing.JPanel();
        AdminBlankPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AdminCusEditPanel = new javax.swing.JPanel();
        CustomerTableView = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        AdminManageconPanel = new javax.swing.JPanel();
        ManageConcertsTableView = new javax.swing.JScrollPane();
        ManageConcertsTable = new javax.swing.JTable();
        EditBookingsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Bookingdeletebtn = new javax.swing.JButton();
        Bookingbackbtn = new javax.swing.JButton();
        AdminBookingsPanel = new javax.swing.JPanel();
        BookTableView = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        EditCustomerPanel = new javax.swing.JPanel();
        EditAccDetailsTitleLbl = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        CreditLbl = new javax.swing.JLabel();
        AddressLbl = new javax.swing.JLabel();
        WebLbl = new javax.swing.JLabel();
        PhoneLbl = new javax.swing.JLabel();
        AccountLbl = new javax.swing.JLabel();
        PassLbl = new javax.swing.JLabel();
        UserLbl = new javax.swing.JLabel();
        EmailLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        CreditTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        WebTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        UsernameTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        AccountTxt = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        backbtnedit = new javax.swing.JButton();
        EditConcertPnl = new javax.swing.JPanel();
        EditConcertDetailsLbl = new javax.swing.JLabel();
        EditConcertNameLbl = new javax.swing.JLabel();
        EditConcertVenueLbl = new javax.swing.JLabel();
        EditConcertTimeLbl = new javax.swing.JLabel();
        EditConcertDateLbl = new javax.swing.JLabel();
        EditConcertVenueTxt = new javax.swing.JTextField();
        EditConcertNameTxt = new javax.swing.JTextField();
        EditPremiumPriceLbl = new javax.swing.JLabel();
        EditStartTimeTxt = new javax.swing.JTextField();
        EditPremiumPriceTxt = new javax.swing.JTextField();
        EditNonPremiumPriceTxt = new javax.swing.JTextField();
        EditCorporatePriceLbl = new javax.swing.JLabel();
        EditCorporatePriceTxt = new javax.swing.JTextField();
        EditNonPremiumPriceLbl = new javax.swing.JLabel();
        UpdateConcertBtn = new javax.swing.JButton();
        DeleteConcertBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        EditStartDateTxt = new javax.swing.JTextField();
        EditEndDateTxt = new javax.swing.JTextField();
        EditEndTimeTxt = new javax.swing.JTextField();
        EndDateLabel = new javax.swing.JLabel();
        EndTimeLabel = new javax.swing.JLabel();
        ErrorDateLabel = new javax.swing.JLabel();
        ErrorTimeLabel = new javax.swing.JLabel();
        InvoicePanel = new javax.swing.JPanel();
        InvoiceTableView = new javax.swing.JScrollPane();
        InvoiceTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        AdminManageBookPanel.setBackground(new java.awt.Color(34, 36, 49));

        javax.swing.GroupLayout AdminManageBookPanelLayout = new javax.swing.GroupLayout(AdminManageBookPanel);
        AdminManageBookPanel.setLayout(AdminManageBookPanelLayout);
        AdminManageBookPanelLayout.setHorizontalGroup(
            AdminManageBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1142, Short.MAX_VALUE)
        );
        AdminManageBookPanelLayout.setVerticalGroup(
            AdminManageBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminConcertsLabel.setBackground(new java.awt.Color(34, 36, 49));

        AdminCustomerLabel.setBackground(new java.awt.Color(34, 36, 49));
        AdminCustomerLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        AdminCustomerLabel.setForeground(new java.awt.Color(0, 102, 204));
        AdminCustomerLabel.setText("View/Edit Customer Account");
        AdminCustomerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminCustomerLabel.setOpaque(true);
        AdminCustomerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminCustomerLabelMouseClicked(evt);
            }
        });

        ManageConcertsLabel.setBackground(new java.awt.Color(34, 36, 49));
        ManageConcertsLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        ManageConcertsLabel.setForeground(new java.awt.Color(0, 102, 204));
        ManageConcertsLabel.setText("Manage Concerts");
        ManageConcertsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageConcertsLabel.setOpaque(true);
        ManageConcertsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageConcertsLabelMouseClicked(evt);
            }
        });

        AdminBookingsLabel.setBackground(new java.awt.Color(34, 36, 49));
        AdminBookingsLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        AdminBookingsLabel.setForeground(new java.awt.Color(0, 102, 204));
        AdminBookingsLabel.setText("Manage Bookings");
        AdminBookingsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminBookingsLabel.setOpaque(true);
        AdminBookingsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminBookingsLabelMouseClicked(evt);
            }
        });

        AdminInvoiceLabel.setBackground(new java.awt.Color(34, 36, 49));
        AdminInvoiceLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        AdminInvoiceLabel.setForeground(new java.awt.Color(0, 102, 204));
        AdminInvoiceLabel.setText("Monthly Invoice");
        AdminInvoiceLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminInvoiceLabel.setOpaque(true);
        AdminInvoiceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminInvoiceLabelMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/gm.png"))); // NOI18N

        LoginInfoLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 13)); // NOI18N
        LoginInfoLabel.setForeground(new java.awt.Color(0, 102, 255));
        LoginInfoLabel.setText("Logged in as Admin");

        GeneralLoginPicLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/human.png"))); // NOI18N

        GeneralLogOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/Logout.jpg"))); // NOI18N
        GeneralLogOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GeneralLogOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneralLogOutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AdminConcertsLabelLayout = new javax.swing.GroupLayout(AdminConcertsLabel);
        AdminConcertsLabel.setLayout(AdminConcertsLabelLayout);
        AdminConcertsLabelLayout.setHorizontalGroup(
            AdminConcertsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminConcertsLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminConcertsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminConcertsLabelLayout.createSequentialGroup()
                        .addComponent(AdminCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManageConcertsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AdminBookingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminConcertsLabelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108)))
                .addGroup(AdminConcertsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminConcertsLabelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GeneralLoginPicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoginInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GeneralLogOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(AdminConcertsLabelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AdminInvoiceLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        AdminConcertsLabelLayout.setVerticalGroup(
            AdminConcertsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminConcertsLabelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(AdminConcertsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminConcertsLabelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(AdminConcertsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GeneralLoginPicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeneralLogOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AdminConcertsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AdminInvoiceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(AdminCustomerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminBookingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(ManageConcertsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        AdminBotPanel.setBackground(new java.awt.Color(34, 36, 49));
        AdminBotPanel.setToolTipText("");
        AdminBotPanel.setLayout(new java.awt.CardLayout());

        AdminBlankPanel.setBackground(new java.awt.Color(34, 36, 49));

        jLabel4.setBackground(new java.awt.Color(34, 36, 49));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome to Global Music. Click the tabs above to Navigate.");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout AdminBlankPanelLayout = new javax.swing.GroupLayout(AdminBlankPanel);
        AdminBlankPanel.setLayout(AdminBlankPanelLayout);
        AdminBlankPanelLayout.setHorizontalGroup(
            AdminBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBlankPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(619, Short.MAX_VALUE))
        );
        AdminBlankPanelLayout.setVerticalGroup(
            AdminBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBlankPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        AdminBotPanel.add(AdminBlankPanel, "card2");

        AdminCusEditPanel.setBackground(new java.awt.Color(34, 36, 49));

        CustomerTable.setBackground(new java.awt.Color(204, 255, 255));
        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        CustomerTableView.setViewportView(CustomerTable);

        javax.swing.GroupLayout AdminCusEditPanelLayout = new javax.swing.GroupLayout(AdminCusEditPanel);
        AdminCusEditPanel.setLayout(AdminCusEditPanelLayout);
        AdminCusEditPanelLayout.setHorizontalGroup(
            AdminCusEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminCusEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerTableView, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
                .addContainerGap())
        );
        AdminCusEditPanelLayout.setVerticalGroup(
            AdminCusEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCusEditPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(CustomerTableView, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        AdminBotPanel.add(AdminCusEditPanel, "card3");

        AdminManageconPanel.setBackground(new java.awt.Color(34, 36, 49));

        ManageConcertsTable.setBackground(new java.awt.Color(204, 255, 255));
        ManageConcertsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ManageConcertsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageConcertsTableMouseClicked(evt);
            }
        });
        ManageConcertsTableView.setViewportView(ManageConcertsTable);

        javax.swing.GroupLayout AdminManageconPanelLayout = new javax.swing.GroupLayout(AdminManageconPanel);
        AdminManageconPanel.setLayout(AdminManageconPanelLayout);
        AdminManageconPanelLayout.setHorizontalGroup(
            AdminManageconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminManageconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManageConcertsTableView, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
                .addContainerGap())
        );
        AdminManageconPanelLayout.setVerticalGroup(
            AdminManageconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminManageconPanelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(ManageConcertsTableView, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        AdminBotPanel.add(AdminManageconPanel, "card4");

        EditBookingsPanel.setBackground(new java.awt.Color(34, 36, 49));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Are you sure you want to delete this booking?");

        Bookingdeletebtn.setBackground(new java.awt.Color(255, 0, 51));
        Bookingdeletebtn.setText("Delete");
        Bookingdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingdeletebtnActionPerformed(evt);
            }
        });

        Bookingbackbtn.setBackground(new java.awt.Color(255, 0, 51));
        Bookingbackbtn.setText("Back");
        Bookingbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingbackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditBookingsPanelLayout = new javax.swing.GroupLayout(EditBookingsPanel);
        EditBookingsPanel.setLayout(EditBookingsPanelLayout);
        EditBookingsPanelLayout.setHorizontalGroup(
            EditBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBookingsPanelLayout.createSequentialGroup()
                .addGroup(EditBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditBookingsPanelLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditBookingsPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Bookingbackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditBookingsPanelLayout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(Bookingdeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        EditBookingsPanelLayout.setVerticalGroup(
            EditBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBookingsPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Bookingbackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Bookingdeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        AdminBotPanel.add(EditBookingsPanel, "card6");

        AdminBookingsPanel.setBackground(new java.awt.Color(34, 36, 49));

        BookTable.setBackground(new java.awt.Color(204, 255, 255));
        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookTableMouseClicked(evt);
            }
        });
        BookTableView.setViewportView(BookTable);

        javax.swing.GroupLayout AdminBookingsPanelLayout = new javax.swing.GroupLayout(AdminBookingsPanel);
        AdminBookingsPanel.setLayout(AdminBookingsPanelLayout);
        AdminBookingsPanelLayout.setHorizontalGroup(
            AdminBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminBookingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookTableView, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
                .addContainerGap())
        );
        AdminBookingsPanelLayout.setVerticalGroup(
            AdminBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBookingsPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(BookTableView, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        AdminBotPanel.add(AdminBookingsPanel, "card6");

        EditCustomerPanel.setBackground(new java.awt.Color(34, 36, 49));

        EditAccDetailsTitleLbl.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 24)); // NOI18N
        EditAccDetailsTitleLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditAccDetailsTitleLbl.setText("Edit Details");

        NameLbl.setBackground(new java.awt.Color(34, 36, 49));
        NameLbl.setForeground(new java.awt.Color(0, 102, 204));
        NameLbl.setText("Name");
        NameLbl.setOpaque(true);

        CreditLbl.setBackground(new java.awt.Color(34, 36, 49));
        CreditLbl.setForeground(new java.awt.Color(0, 102, 204));
        CreditLbl.setText("Credit No");
        CreditLbl.setOpaque(true);

        AddressLbl.setBackground(new java.awt.Color(34, 36, 49));
        AddressLbl.setForeground(new java.awt.Color(0, 102, 204));
        AddressLbl.setText("Address");
        AddressLbl.setOpaque(true);

        WebLbl.setBackground(new java.awt.Color(34, 36, 49));
        WebLbl.setForeground(new java.awt.Color(0, 102, 204));
        WebLbl.setText("Web Address");
        WebLbl.setOpaque(true);

        PhoneLbl.setBackground(new java.awt.Color(34, 36, 49));
        PhoneLbl.setForeground(new java.awt.Color(0, 102, 204));
        PhoneLbl.setText("Phone Number");
        PhoneLbl.setOpaque(true);

        AccountLbl.setBackground(new java.awt.Color(34, 36, 49));
        AccountLbl.setForeground(new java.awt.Color(0, 102, 204));
        AccountLbl.setText("Account Type");
        AccountLbl.setOpaque(true);

        PassLbl.setBackground(new java.awt.Color(34, 36, 49));
        PassLbl.setForeground(new java.awt.Color(0, 102, 204));
        PassLbl.setText("Password");
        PassLbl.setOpaque(true);

        UserLbl.setBackground(new java.awt.Color(34, 36, 49));
        UserLbl.setForeground(new java.awt.Color(0, 102, 204));
        UserLbl.setText("Username");
        UserLbl.setOpaque(true);

        EmailLbl.setBackground(new java.awt.Color(34, 36, 49));
        EmailLbl.setForeground(new java.awt.Color(0, 102, 204));
        EmailLbl.setText("Email");
        EmailLbl.setOpaque(true);

        PhoneTxt.setToolTipText("");

        updatebtn.setBackground(new java.awt.Color(255, 0, 51));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        backbtnedit.setBackground(new java.awt.Color(255, 0, 51));
        backbtnedit.setText("Back");
        backbtnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtneditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditCustomerPanelLayout = new javax.swing.GroupLayout(EditCustomerPanel);
        EditCustomerPanel.setLayout(EditCustomerPanelLayout);
        EditCustomerPanelLayout.setHorizontalGroup(
            EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditCustomerPanelLayout.createSequentialGroup()
                        .addComponent(EditAccDetailsTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                                .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditCustomerPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(UserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65))
                                    .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                                                .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(NameLbl)
                                                    .addComponent(PhoneLbl)
                                                    .addComponent(WebLbl)
                                                    .addComponent(AddressLbl))
                                                .addGap(73, 73, 73)
                                                .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(WebTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                                    .addComponent(NameTxt)
                                                    .addComponent(PhoneTxt)
                                                    .addComponent(AddressTxt)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditCustomerPanelLayout.createSequentialGroup()
                                                .addComponent(CreditLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(94, 94, 94)
                                                .addComponent(CreditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditCustomerPanelLayout.createSequentialGroup()
                                                .addComponent(PassLbl)
                                                .addGap(70, 70, 70))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditCustomerPanelLayout.createSequentialGroup()
                                                .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(AccountLbl)
                                                    .addComponent(EmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48)))))
                                .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UsernameTxt)
                                    .addComponent(PasswordTxt)
                                    .addComponent(AccountTxt)
                                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditCustomerPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(backbtnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGap(124, 124, 124))))
        );
        EditCustomerPanelLayout.setVerticalGroup(
            EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditAccDetailsTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserLbl)
                        .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(PassLbl))
                            .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccountLbl))
                        .addGap(52, 52, 52)
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backbtnedit)
                            .addComponent(updatebtn)))
                    .addGroup(EditCustomerPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreditLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WebTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WebLbl))
                        .addGap(18, 18, 18)
                        .addGroup(EditCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneLbl))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        AdminBotPanel.add(EditCustomerPanel, "card7");

        EditConcertPnl.setBackground(new java.awt.Color(34, 36, 49));

        EditConcertDetailsLbl.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 24)); // NOI18N
        EditConcertDetailsLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditConcertDetailsLbl.setText("Edit your Concert Details");

        EditConcertNameLbl.setBackground(new java.awt.Color(34, 36, 49));
        EditConcertNameLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditConcertNameLbl.setText("Name");
        EditConcertNameLbl.setOpaque(true);

        EditConcertVenueLbl.setBackground(new java.awt.Color(34, 36, 49));
        EditConcertVenueLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditConcertVenueLbl.setText("Venue");
        EditConcertVenueLbl.setOpaque(true);

        EditConcertTimeLbl.setBackground(new java.awt.Color(34, 36, 49));
        EditConcertTimeLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditConcertTimeLbl.setText("Start Time");
        EditConcertTimeLbl.setOpaque(true);

        EditConcertDateLbl.setBackground(new java.awt.Color(34, 36, 49));
        EditConcertDateLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditConcertDateLbl.setText("Start Date");
        EditConcertDateLbl.setOpaque(true);

        EditPremiumPriceLbl.setBackground(new java.awt.Color(34, 36, 49));
        EditPremiumPriceLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditPremiumPriceLbl.setText("Premium Price");
        EditPremiumPriceLbl.setOpaque(true);

        EditStartTimeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditStartTimeTxtKeyReleased(evt);
            }
        });

        EditCorporatePriceLbl.setBackground(new java.awt.Color(34, 36, 49));
        EditCorporatePriceLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditCorporatePriceLbl.setText("Corporate Price");
        EditCorporatePriceLbl.setOpaque(true);

        EditNonPremiumPriceLbl.setBackground(new java.awt.Color(34, 36, 49));
        EditNonPremiumPriceLbl.setForeground(new java.awt.Color(0, 102, 204));
        EditNonPremiumPriceLbl.setText("Non Premium Price");
        EditNonPremiumPriceLbl.setOpaque(true);

        UpdateConcertBtn.setBackground(new java.awt.Color(255, 0, 51));
        UpdateConcertBtn.setText("Update Details");
        UpdateConcertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateConcertBtnActionPerformed(evt);
            }
        });

        DeleteConcertBtn.setBackground(new java.awt.Color(255, 0, 51));
        DeleteConcertBtn.setText("Cancel Concert");
        DeleteConcertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteConcertBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(255, 51, 51));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        EditStartDateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditStartDateTxtKeyReleased(evt);
            }
        });

        EditEndDateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditEndDateTxtKeyReleased(evt);
            }
        });

        EditEndTimeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditEndTimeTxtKeyReleased(evt);
            }
        });

        EndDateLabel.setBackground(new java.awt.Color(34, 36, 49));
        EndDateLabel.setForeground(new java.awt.Color(0, 102, 204));
        EndDateLabel.setText("End Date");
        EndDateLabel.setOpaque(true);

        EndTimeLabel.setBackground(new java.awt.Color(34, 36, 49));
        EndTimeLabel.setForeground(new java.awt.Color(0, 102, 204));
        EndTimeLabel.setText("End Time");
        EndTimeLabel.setOpaque(true);

        ErrorDateLabel.setBackground(new java.awt.Color(34, 36, 49));
        ErrorDateLabel.setForeground(new java.awt.Color(255, 0, 51));
        ErrorDateLabel.setOpaque(true);

        ErrorTimeLabel.setBackground(new java.awt.Color(34, 36, 49));
        ErrorTimeLabel.setForeground(new java.awt.Color(255, 0, 51));
        ErrorTimeLabel.setOpaque(true);

        javax.swing.GroupLayout EditConcertPnlLayout = new javax.swing.GroupLayout(EditConcertPnl);
        EditConcertPnl.setLayout(EditConcertPnlLayout);
        EditConcertPnlLayout.setHorizontalGroup(
            EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditConcertPnlLayout.createSequentialGroup()
                        .addComponent(EditConcertDetailsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EditConcertPnlLayout.createSequentialGroup()
                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EditConcertTimeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EditConcertDateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(EditConcertVenueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                        .addComponent(EditConcertNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EditConcertVenueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                                        .addComponent(EditStartTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(EndTimeLabel))
                                                    .addComponent(EditStartDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                                        .addComponent(EndDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(EditEndDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(EditEndTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(ErrorDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE))))
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditConcertNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BackBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addComponent(EditNonPremiumPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditNonPremiumPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addComponent(EditPremiumPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditPremiumPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addComponent(EditCorporatePriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditCorporatePriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(142, 142, 142))))
            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ErrorTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateConcertBtn))
                .addGap(62, 62, 62)
                .addComponent(DeleteConcertBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditConcertPnlLayout.setVerticalGroup(
            EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(BackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditConcertDetailsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditConcertPnlLayout.createSequentialGroup()
                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditConcertNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditPremiumPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditPremiumPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditNonPremiumPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditNonPremiumPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditCorporatePriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditCorporatePriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateConcertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteConcertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(EditConcertPnlLayout.createSequentialGroup()
                        .addComponent(EditConcertNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EditConcertDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditStartDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EditConcertVenueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditConcertVenueLbl))
                                .addGap(18, 18, 18)
                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EditEndDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EndDateLabel))))
                        .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(ErrorDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EditConcertPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EditConcertTimeLbl)
                                    .addComponent(EditStartTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditEndTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EndTimeLabel)))
                            .addGroup(EditConcertPnlLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(ErrorTimeLabel))))))
        );

        AdminBotPanel.add(EditConcertPnl, "card4");

        InvoicePanel.setBackground(new java.awt.Color(34, 36, 49));

        InvoiceTable.setBackground(new java.awt.Color(204, 255, 255));
        InvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        InvoiceTableView.setViewportView(InvoiceTable);

        jLabel2.setBackground(new java.awt.Color(34, 36, 49));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("INVOICE");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout InvoicePanelLayout = new javax.swing.GroupLayout(InvoicePanel);
        InvoicePanel.setLayout(InvoicePanelLayout);
        InvoicePanelLayout.setHorizontalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvoiceTableView)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelLayout.createSequentialGroup()
                .addContainerGap(584, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(535, 535, 535))
        );
        InvoicePanelLayout.setVerticalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(InvoiceTableView, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        AdminBotPanel.add(InvoicePanel, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminConcertsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdminBotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AdminConcertsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminBotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
        
    private void AdminCustomerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminCustomerLabelMouseClicked
        
        AdminCustomerLabel.setBackground(new java.awt.Color(255,255,255));
        ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));
        AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
        AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));


        
        AdminBotPanel.removeAll();
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        AdminBotPanel.add(AdminCusEditPanel);
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        
        PreparedStatement ps;
        ResultSet rs;
         try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String sql = "select * from user_info;";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            CustomerTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_AdminCustomerLabelMouseClicked

    private void ManageConcertsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageConcertsLabelMouseClicked
        
        ManageConcertsLabel.setBackground(new java.awt.Color(255,255,255));
        AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
        AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
        AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));


        
        AdminBotPanel.removeAll();
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        AdminBotPanel.add(AdminManageconPanel);
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        
        try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String sql = "SELECT * from concert_info, concert_schedule where concert_info.concert_id = concert_schedule.concert_id;";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ManageConcertsTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }  
                
        
    }//GEN-LAST:event_ManageConcertsLabelMouseClicked

    private void AdminBookingsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBookingsLabelMouseClicked
        
        AdminBookingsLabel.setBackground(new java.awt.Color(255,255,255));
        AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
        ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));
        AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));


        
        AdminBotPanel.removeAll();
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        AdminBotPanel.add(AdminBookingsPanel);
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        
        
        try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String sql = "select * from book_info;";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            BookTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }  
        
        
        
    }//GEN-LAST:event_AdminBookingsLabelMouseClicked

    private void AdminInvoiceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminInvoiceLabelMouseClicked
        
        AdminInvoiceLabel.setBackground(new java.awt.Color(255,255,255));
        AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
        AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
        ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));


        
        AdminBotPanel.removeAll();
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        AdminBotPanel.add(InvoicePanel);
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        
         try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String sql = "SELECT ticket_booker,booking_id, book_info.concert_id,concert_name,  ticket_type, tickets_bought, total_price, book_time, paid_status from concert_info, book_info WHERE book_info.concert_id = concert_info.concert_id AND DATE_ADD(CURDATE(), INTERVAL 1 DAY) - book_time <30;";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            InvoiceTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_AdminInvoiceLabelMouseClicked

    public String customer_username;
    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        
        AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));
        AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
        AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
        ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));


        
        AdminBotPanel.removeAll();
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        AdminBotPanel.add(EditCustomerPanel);
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        
        
        
        
        try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            DefaultTableModel model = (DefaultTableModel)CustomerTable.getModel();

            int selectedRowIndex = CustomerTable.getSelectedRow();

            customer_username = model.getValueAt(selectedRowIndex, 0).toString();
            
            String query = "select * from user_info where username=?";
            ps = con.prepareStatement(query); 
            ps.setString(1, customer_username);
            rs = ps.executeQuery();
            
            if(rs.next())
            {   
                
                UsernameTxt.setText(rs.getString(1));
                NameTxt.setText(rs.getString(3));
                CreditTxt.setText(rs.getString(7));
                AddressTxt.setText(rs.getString(5));
                WebTxt.setText(rs.getString(9));
                PhoneTxt.setText(rs.getString(6));
                PasswordTxt.setText(rs.getString(2));
                EmailTxt.setText(rs.getString(4));
                AccountTxt.setText(rs.getString(8));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Not Connected");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
     
        
        try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");        
            String query = "update user_info set username =?, password=?, name=?, email=?, creditno=?, address=?, web_address=?, phoneno=?, account_type=?" + "where username=?";
            ps = con.prepareStatement(query);
            
            
            
            ps.setString(1, UsernameTxt.getText());
            ps.setString(2, PasswordTxt.getText());
            ps.setString(3, NameTxt.getText());
            ps.setString(4, EmailTxt.getText());
            ps.setString(5, CreditTxt.getText());
            ps.setString(6, AddressTxt.getText());
            ps.setString(7, WebTxt.getText());
            ps.setString(8, PhoneTxt.getText());
            ps.setString(9, AccountTxt.getText());
            
            ps.setString(10,customer_username );
            
            ps.executeUpdate();           
            ps.addBatch();

            JOptionPane.showMessageDialog(null, "Data updated successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Data couldn't be updated. Check your datatypes");
            NameTxt.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_updatebtnActionPerformed

    private void backbtneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtneditActionPerformed
        
        
        AdminCustomerLabel.setBackground(new java.awt.Color(255,255,255));
        AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));
        AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
        ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));


        
        AdminBotPanel.removeAll();
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();
        AdminBotPanel.add(AdminCusEditPanel);
        AdminBotPanel.repaint();
        AdminBotPanel.revalidate();    
        ErrorDateLabel.setText(null);
        ErrorDateLabel.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_backbtneditActionPerformed

    public int manageconcertid;
    private void UpdateConcertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateConcertBtnActionPerformed
        // TODO add your handling code here:
        
        
        String PATTERN1 = "^[0-9]{1,2}[:][0-9]{1,2}[:][0-9]{1,2}$";
        String PATTERN = "^[0-9]{4,5}[-][0-9]{0,3}[-][0-9]{1,15}$";
        Pattern patt1 = Pattern.compile(PATTERN1);
        Matcher match1 = patt1.matcher(EditStartTimeTxt.getText());
        Matcher match2 = patt1.matcher(EditEndTimeTxt.getText());
        
        if(!match1.matches() || !match2.matches()){
            ErrorTimeLabel.setText("Incorrect format (hh:mm:ss)");
        }
        else{
            ErrorTimeLabel.setText(null);
                
            
            Pattern patt = Pattern.compile(PATTERN);
            Matcher match3 = patt.matcher(EditStartDateTxt.getText());
            Matcher match4 = patt.matcher(EditEndDateTxt.getText());
        
            if(!match3.matches() || !match4.matches()){
                ErrorDateLabel.setText("Incorrect format (yyyy-mm-dd)");
               }
            else{
                ErrorDateLabel.setText(null);
                     
        try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String query1 = "update concert_info set concert_name=?, concert_venue=?, ticketa_price=?, ticketb_price=?, ticketc_price=?" + "where concert_id=?";
            String query2=  "update concert_schedule set start_date=?, end_date=?, start_time=?, end_time=?" + "where concert_id=?";
            ps = con.prepareStatement(query1);

            ps.setString(1, EditConcertNameTxt.getText());
            ps.setString(2, EditConcertVenueTxt.getText());
            ps.setString(3, EditPremiumPriceTxt.getText());
            ps.setString(4, EditNonPremiumPriceTxt.getText());
            ps.setString(5, EditCorporatePriceTxt.getText());
            ps.setInt(6, manageconcertid);
            ps.executeUpdate();
            ps.addBatch();
            
            ps=con.prepareStatement(query2);
            
            ps.setString(1, EditStartDateTxt.getText());
            ps.setString(2, EditEndDateTxt.getText());
            ps.setString(3, EditStartTimeTxt.getText());
            ps.setString(4, EditEndTimeTxt.getText());
            ps.setInt(5, manageconcertid);
            ps.executeUpdate();
            ps.addBatch();
            
            JOptionPane.showMessageDialog(null, "Data updated successfully");

            AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));
            AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
            AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
            ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));

            AdminBotPanel.removeAll();
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
            AdminBotPanel.add(AdminBlankPanel);
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null, "Data couldn't be inserted");
            NameTxt.requestFocus();
        }}}
    }//GEN-LAST:event_UpdateConcertBtnActionPerformed

    private void DeleteConcertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteConcertBtnActionPerformed
        // TODO add your handling code here:
        
        
        try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String query = "delete from concert_info where concert_id=?";

            ps = con.prepareStatement(query);
            ps.setInt(1, manageconcertid);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Concert Deleted Successfully");


            AdminBotPanel.removeAll();
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
            AdminBotPanel.add(AdminBlankPanel);
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null, "Data couldn't be deleted");
            EditConcertNameTxt.requestFocus();
        }
    }//GEN-LAST:event_DeleteConcertBtnActionPerformed

    private void ManageConcertsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageConcertsTableMouseClicked
        
        AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));
        AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
        AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
        ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));
        
            AdminBotPanel.removeAll();
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
            AdminBotPanel.add(EditConcertPnl);
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate(); 
       
        
        try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            DefaultTableModel model = (DefaultTableModel)ManageConcertsTable.getModel();

            int selectedRowIndex = ManageConcertsTable.getSelectedRow();

            manageconcertid = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
            
            String query = "select concert_info.concert_id, concert_name, concert_venue, concert_createdby, ticketa_price, ticketb_price, ticketc_price, sponsor, start_date,end_date,start_time, end_time from concert_info,concert_schedule where concert_info.concert_id = concert_schedule.concert_id AND concert_info.concert_id =?;";
            ps = con.prepareStatement(query); 
            ps.setInt(1, manageconcertid);
            rs = ps.executeQuery();
            
            if(rs.next())
            {   
                
                EditConcertNameTxt.setText(rs.getString(2));
                EditConcertVenueTxt.setText(rs.getString(3));
                EditStartDateTxt.setText(rs.getString(9));
                EditStartTimeTxt.setText(rs.getString(11));
                EditEndDateTxt.setText(rs.getString(10));
                EditEndTimeTxt.setText(rs.getString(12));
                EditPremiumPriceTxt.setText(rs.getString(5));
                EditNonPremiumPriceTxt.setText(rs.getString(6));
                EditCorporatePriceTxt.setText(rs.getString(7));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null, "Not Connected");
        } 
       


// TODO add your handling code here:
    }//GEN-LAST:event_ManageConcertsTableMouseClicked
public int managebookingid;
    private void BookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTableMouseClicked
        
        
            AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));
            AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
            AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
            ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));  
        
        
            AdminBotPanel.removeAll();
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
            AdminBotPanel.add(EditBookingsPanel);
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate(); 
            
            try{  
                con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
                DefaultTableModel model = (DefaultTableModel)BookTable.getModel();
            
            //get the selected row index
                int selectedRowIndex = BookTable.getSelectedRow();
            
            //set the selected row data into JLabels
                managebookingid = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
            
        }
// TODO add your handling code here:
    }//GEN-LAST:event_BookTableMouseClicked

    private void BookingdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingdeletebtnActionPerformed
     
        
        try
        {   
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String query = "delete from book_info where booking_id=?";

            ps = con.prepareStatement(query);
            ps.setInt(1, managebookingid);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Booking Deleted Successfully");

               
            
            AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));
            AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
            AdminBookingsLabel.setBackground(new java.awt.Color(34,36,49));
            ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));  
            
            AdminBotPanel.removeAll();
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
            AdminBotPanel.add(AdminBlankPanel);
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null, "Data couldn't be deleted");
            EditConcertNameTxt.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_BookingdeletebtnActionPerformed

    private void BookingbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingbackbtnActionPerformed
            AdminInvoiceLabel.setBackground(new java.awt.Color(34,36,49));
            AdminCustomerLabel.setBackground(new java.awt.Color(34,36,49));
            AdminBookingsLabel.setBackground(new java.awt.Color(255,255,255));
            ManageConcertsLabel.setBackground(new java.awt.Color(34,36,49));  
        
        
            AdminBotPanel.removeAll();
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
            AdminBotPanel.add(AdminBookingsPanel);
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();   
            ErrorDateLabel.setText(null);
            ErrorTimeLabel.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_BookingbackbtnActionPerformed

    private void GeneralLogOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneralLogOutLabelMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_GeneralLogOutLabelMouseClicked

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
            AdminBotPanel.removeAll();
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();
            AdminBotPanel.add(AdminManageconPanel);
            AdminBotPanel.repaint();
            AdminBotPanel.revalidate();   
            ErrorDateLabel.setText(null);
            ErrorTimeLabel.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void EditStartDateTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditStartDateTxtKeyReleased
        String PATTERN = "^[0-9]{4,5}[-][0-9]{0,3}[-][0-9]{1,15}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(EditStartDateTxt.getText());
        
        if(!match.matches()){
            ErrorDateLabel.setText("Incorrect format (yyyy-mm-dd)");
        }
        else{
            ErrorDateLabel.setText(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_EditStartDateTxtKeyReleased

    private void EditEndDateTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditEndDateTxtKeyReleased
        String PATTERN = "^[0-9]{4,5}[-][0-9]{0,3}[-][0-9]{1,15}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(EditStartDateTxt.getText());
        
        if(!match.matches()){
            ErrorDateLabel.setText("Incorrect format (yyyy-mm-dd)");
        }
        else{
            ErrorDateLabel.setText(null);
        }              // TODO add your handling code here:
    }//GEN-LAST:event_EditEndDateTxtKeyReleased

    private void EditStartTimeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditStartTimeTxtKeyReleased
        String PATTERN = "^[0-9]{1,2}[:][0-9]{1,2}[:][0-9]{1,2}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(EditStartTimeTxt.getText());
        
        if(!match.matches()){
            ErrorTimeLabel.setText("Incorrect format (hh:mm:ss)");
        }
        else{
            ErrorTimeLabel.setText(null);
        }              // TODO add your handling code here:
    }//GEN-LAST:event_EditStartTimeTxtKeyReleased

    private void EditEndTimeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditEndTimeTxtKeyReleased
        String PATTERN = "^[0-9]{1,2}[:][0-9]{1,2}[:][0-9]{1,2}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(EditStartTimeTxt.getText());
        
        if(!match.matches()){
            ErrorTimeLabel.setText("Incorrect format (hh:mm:ss)");
        }
        else{
            ErrorTimeLabel.setText(null);
        }                // TODO add your handling code here:
    }//GEN-LAST:event_EditEndTimeTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountLbl;
    private javax.swing.JTextField AccountTxt;
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JPanel AdminBlankPanel;
    private javax.swing.JLabel AdminBookingsLabel;
    private javax.swing.JPanel AdminBookingsPanel;
    private javax.swing.JPanel AdminBotPanel;
    private javax.swing.JPanel AdminConcertsLabel;
    private javax.swing.JPanel AdminCusEditPanel;
    private javax.swing.JLabel AdminCustomerLabel;
    private javax.swing.JLabel AdminInvoiceLabel;
    private javax.swing.JPanel AdminManageBookPanel;
    private javax.swing.JPanel AdminManageconPanel;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTable BookTable;
    private javax.swing.JScrollPane BookTableView;
    private javax.swing.JButton Bookingbackbtn;
    private javax.swing.JButton Bookingdeletebtn;
    private javax.swing.JLabel CreditLbl;
    private javax.swing.JTextField CreditTxt;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JScrollPane CustomerTableView;
    private javax.swing.JButton DeleteConcertBtn;
    private javax.swing.JLabel EditAccDetailsTitleLbl;
    private javax.swing.JPanel EditBookingsPanel;
    private javax.swing.JLabel EditConcertDateLbl;
    private javax.swing.JLabel EditConcertDetailsLbl;
    private javax.swing.JLabel EditConcertNameLbl;
    private javax.swing.JTextField EditConcertNameTxt;
    private javax.swing.JPanel EditConcertPnl;
    private javax.swing.JLabel EditConcertTimeLbl;
    private javax.swing.JLabel EditConcertVenueLbl;
    private javax.swing.JTextField EditConcertVenueTxt;
    private javax.swing.JLabel EditCorporatePriceLbl;
    private javax.swing.JTextField EditCorporatePriceTxt;
    private javax.swing.JPanel EditCustomerPanel;
    private javax.swing.JTextField EditEndDateTxt;
    private javax.swing.JTextField EditEndTimeTxt;
    private javax.swing.JLabel EditNonPremiumPriceLbl;
    private javax.swing.JTextField EditNonPremiumPriceTxt;
    private javax.swing.JLabel EditPremiumPriceLbl;
    private javax.swing.JTextField EditPremiumPriceTxt;
    private javax.swing.JTextField EditStartDateTxt;
    private javax.swing.JTextField EditStartTimeTxt;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel EndDateLabel;
    private javax.swing.JLabel EndTimeLabel;
    private javax.swing.JLabel ErrorDateLabel;
    private javax.swing.JLabel ErrorTimeLabel;
    private javax.swing.JLabel GeneralLogOutLabel;
    private javax.swing.JLabel GeneralLoginPicLabel;
    private javax.swing.JPanel InvoicePanel;
    private javax.swing.JTable InvoiceTable;
    private javax.swing.JScrollPane InvoiceTableView;
    private javax.swing.JLabel LoginInfoLabel;
    private javax.swing.JLabel ManageConcertsLabel;
    private javax.swing.JTable ManageConcertsTable;
    private javax.swing.JScrollPane ManageConcertsTableView;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JLabel PhoneLbl;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JButton UpdateConcertBtn;
    private javax.swing.JLabel UserLbl;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JLabel WebLbl;
    private javax.swing.JTextField WebTxt;
    private javax.swing.JButton backbtnedit;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
