/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beta;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
import java.util.regex.*;
import java.util.Date;

public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public static String username, accountType;

    public Homepage(String var1, String var2) {
        initComponents();
        username = var1;
        accountType = var2; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCorporate = new javax.swing.ButtonGroup();
        GeneralHomePagePanel = new javax.swing.JPanel();
        GeneralLoginInfoLabel = new javax.swing.JLabel();
        GeneralEditLoginDetailsBtn = new javax.swing.JButton();
        GeneralLoginPicLabel = new javax.swing.JLabel();
        GeneralLogOutLabel = new javax.swing.JLabel();
        GeneralTitleLabel = new javax.swing.JLabel();
        GeneralMybookingLabel = new javax.swing.JLabel();
        GeneralViewConcertsLabel = new javax.swing.JLabel();
        GeneralPaymentLabel = new javax.swing.JLabel();
        lblmainicon = new javax.swing.JLabel();
        GeneralBotPanel = new javax.swing.JPanel();
        BlankPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GeneralViewConcertsPanel = new javax.swing.JPanel();
        GeneralViewTable = new javax.swing.JScrollPane();
        ViewTable = new javax.swing.JTable();
        GeneralEditDetailsPanel = new javax.swing.JPanel();
        GeneralEditTitleLabel = new javax.swing.JLabel();
        GeneralEditNameLabel = new javax.swing.JLabel();
        GeneralEditAccountLabel = new javax.swing.JLabel();
        GeneralEditAddressTxtbox = new javax.swing.JTextField();
        GeneralEditWebAdressLabel = new javax.swing.JLabel();
        GeneralEditAddressLabel = new javax.swing.JLabel();
        GeneralEditAccountTxtbox = new javax.swing.JTextField();
        GeneralEditPhoneTxtbox = new javax.swing.JTextField();
        GeneralEditPhoneNumberLabel = new javax.swing.JLabel();
        GeneralEditWebTxtbox = new javax.swing.JTextField();
        GeneralEditNameTxtbox = new javax.swing.JTextField();
        GeneralEditPasswordTxtbox = new javax.swing.JTextField();
        GeneralEditPasswordLabel = new javax.swing.JLabel();
        PassifreqdLabel = new javax.swing.JLabel();
        GeneralEditDetailsOkbtn = new javax.swing.JButton();
        GeneralPaymentPanel = new javax.swing.JPanel();
        GeneralPaidLabel = new javax.swing.JLabel();
        CorporatePaymentPanel = new javax.swing.JPanel();
        CoporatePayment = new javax.swing.JScrollPane();
        CorporatePaymentTable = new javax.swing.JTable();
        PaymentButton = new javax.swing.JButton();
        MyBookingPanel = new javax.swing.JPanel();
        GeneralBookTable = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        CorporateBookingPanel = new javax.swing.JPanel();
        BookTableScroll = new javax.swing.JScrollPane();
        BookTable1 = new javax.swing.JTable();
        btnBookCorporate = new javax.swing.JButton();
        CorporateTicketTxtfield = new javax.swing.JTextField();
        BookcorLabel = new javax.swing.JLabel();
        btnBackCorporate = new javax.swing.JButton();
        CorporateErrorLabel = new javax.swing.JLabel();
        BandTableCorView = new javax.swing.JScrollPane();
        BandTableCor = new javax.swing.JTable();
        GeneralBookingPanel = new javax.swing.JPanel();
        BookTableScroll1 = new javax.swing.JScrollPane();
        BookTable2 = new javax.swing.JTable();
        BookPremiumRadio = new javax.swing.JRadioButton();
        BookNonPremiumRadio = new javax.swing.JRadioButton();
        btnBookGeneral = new javax.swing.JButton();
        btnBackGeneral = new javax.swing.JButton();
        BandTableScroll = new javax.swing.JScrollPane();
        BandTable = new javax.swing.JTable();
        GeneralTicketTxtfield = new javax.swing.JTextField();
        BookcorLabel1 = new javax.swing.JLabel();
        GeneralErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GeneralHomePagePanel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralHomePagePanel.setForeground(new java.awt.Color(79, 91, 201));
        GeneralHomePagePanel.setToolTipText("");

        GeneralLoginInfoLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 13)); // NOI18N
        GeneralLoginInfoLabel.setForeground(new java.awt.Color(0, 102, 255));
        GeneralLoginInfoLabel.setText("Logged in");

        GeneralEditLoginDetailsBtn.setBackground(new java.awt.Color(0, 102, 255));
        GeneralEditLoginDetailsBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 13)); // NOI18N
        GeneralEditLoginDetailsBtn.setText("Edit Account Details");
        GeneralEditLoginDetailsBtn.setBorderPainted(false);
        GeneralEditLoginDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GeneralEditLoginDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneralEditLoginDetailsBtnActionPerformed(evt);
            }
        });

        GeneralLoginPicLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/human.png"))); // NOI18N

        GeneralLogOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/Logout.jpg"))); // NOI18N
        GeneralLogOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GeneralLogOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneralLogOutLabelMouseClicked(evt);
            }
        });

        GeneralTitleLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        GeneralTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralTitleLabel.setText("Global Music");

        GeneralMybookingLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralMybookingLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        GeneralMybookingLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralMybookingLabel.setText("My bookings");
        GeneralMybookingLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GeneralMybookingLabel.setOpaque(true);
        GeneralMybookingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneralMybookingLabelMouseClicked(evt);
            }
        });

        GeneralViewConcertsLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralViewConcertsLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        GeneralViewConcertsLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralViewConcertsLabel.setText("View Concerts ");
        GeneralViewConcertsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GeneralViewConcertsLabel.setOpaque(true);
        GeneralViewConcertsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneralViewConcertsLabelMouseClicked(evt);
            }
        });

        GeneralPaymentLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralPaymentLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        GeneralPaymentLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralPaymentLabel.setText("Payments");
        GeneralPaymentLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GeneralPaymentLabel.setOpaque(true);
        GeneralPaymentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneralPaymentLabelMouseClicked(evt);
            }
        });

        lblmainicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/gm.png"))); // NOI18N

        javax.swing.GroupLayout GeneralHomePagePanelLayout = new javax.swing.GroupLayout(GeneralHomePagePanel);
        GeneralHomePagePanel.setLayout(GeneralHomePagePanelLayout);
        GeneralHomePagePanelLayout.setHorizontalGroup(
            GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralHomePagePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralHomePagePanelLayout.createSequentialGroup()
                        .addComponent(GeneralTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmainicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralHomePagePanelLayout.createSequentialGroup()
                                .addComponent(GeneralLoginPicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GeneralLoginInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GeneralLogOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(GeneralEditLoginDetailsBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(43, 43, 43))
                    .addGroup(GeneralHomePagePanelLayout.createSequentialGroup()
                        .addComponent(GeneralMybookingLabel)
                        .addGap(45, 45, 45)
                        .addComponent(GeneralViewConcertsLabel)
                        .addGap(58, 58, 58)
                        .addComponent(GeneralPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        GeneralHomePagePanelLayout.setVerticalGroup(
            GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralHomePagePanelLayout.createSequentialGroup()
                .addGroup(GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralHomePagePanelLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneralHomePagePanelLayout.createSequentialGroup()
                                .addGroup(GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(GeneralLogOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GeneralLoginPicLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(GeneralLoginInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GeneralEditLoginDetailsBtn))
                            .addGroup(GeneralHomePagePanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(GeneralTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(GeneralHomePagePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblmainicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(GeneralHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GeneralMybookingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneralPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneralViewConcertsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        GeneralLoginInfoLabel.getAccessibleContext().setAccessibleName("");
        GeneralLoginInfoLabel.getAccessibleContext().setAccessibleDescription("");
        GeneralEditLoginDetailsBtn.getAccessibleContext().setAccessibleName("EditDetailsbtn");
        GeneralLoginPicLabel.getAccessibleContext().setAccessibleName("LoginIconLabel");

        GeneralBotPanel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralBotPanel.setLayout(new java.awt.CardLayout());

        BlankPanel.setBackground(new java.awt.Color(34, 36, 49));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Global Music. Navigate above to continue!");

        javax.swing.GroupLayout BlankPanelLayout = new javax.swing.GroupLayout(BlankPanel);
        BlankPanel.setLayout(BlankPanelLayout);
        BlankPanelLayout.setHorizontalGroup(
            BlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlankPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        BlankPanelLayout.setVerticalGroup(
            BlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlankPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        GeneralBotPanel.add(BlankPanel, "card7");

        GeneralViewConcertsPanel.setBackground(new java.awt.Color(34, 36, 49));

        GeneralViewTable.setBackground(new java.awt.Color(51, 255, 0));

        ViewTable.setBackground(new java.awt.Color(204, 255, 255));
        ViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Venue", "Date", "Time", "Premium Price", "Non Premium Price", "Corporate Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewTable.getTableHeader().setReorderingAllowed(false);
        ViewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewTableMouseClicked(evt);
            }
        });
        GeneralViewTable.setViewportView(ViewTable);
        if (ViewTable.getColumnModel().getColumnCount() > 0) {
            ViewTable.getColumnModel().getColumn(0).setResizable(false);
            ViewTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            ViewTable.getColumnModel().getColumn(1).setResizable(false);
            ViewTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            ViewTable.getColumnModel().getColumn(2).setResizable(false);
            ViewTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            ViewTable.getColumnModel().getColumn(3).setResizable(false);
            ViewTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            ViewTable.getColumnModel().getColumn(4).setResizable(false);
            ViewTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            ViewTable.getColumnModel().getColumn(5).setResizable(false);
            ViewTable.getColumnModel().getColumn(6).setResizable(false);
            ViewTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout GeneralViewConcertsPanelLayout = new javax.swing.GroupLayout(GeneralViewConcertsPanel);
        GeneralViewConcertsPanel.setLayout(GeneralViewConcertsPanelLayout);
        GeneralViewConcertsPanelLayout.setHorizontalGroup(
            GeneralViewConcertsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralViewConcertsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralViewTable, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
                .addContainerGap())
        );
        GeneralViewConcertsPanelLayout.setVerticalGroup(
            GeneralViewConcertsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralViewConcertsPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(GeneralViewTable, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        GeneralBotPanel.add(GeneralViewConcertsPanel, "card3");

        GeneralEditDetailsPanel.setBackground(new java.awt.Color(34, 36, 49));

        GeneralEditTitleLabel.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 24)); // NOI18N
        GeneralEditTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralEditTitleLabel.setText("Edit your details ");

        GeneralEditNameLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralEditNameLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralEditNameLabel.setText("Name");
        GeneralEditNameLabel.setOpaque(true);

        GeneralEditAccountLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralEditAccountLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralEditAccountLabel.setText("Account No");
        GeneralEditAccountLabel.setOpaque(true);

        GeneralEditWebAdressLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralEditWebAdressLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralEditWebAdressLabel.setText("Web Address");
        GeneralEditWebAdressLabel.setOpaque(true);

        GeneralEditAddressLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralEditAddressLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralEditAddressLabel.setText("Address");
        GeneralEditAddressLabel.setOpaque(true);

        GeneralEditPhoneNumberLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralEditPhoneNumberLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralEditPhoneNumberLabel.setText("Phone Number");
        GeneralEditPhoneNumberLabel.setOpaque(true);

        GeneralEditPasswordLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralEditPasswordLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralEditPasswordLabel.setText("Password");
        GeneralEditPasswordLabel.setOpaque(true);

        PassifreqdLabel.setBackground(new java.awt.Color(0, 102, 204));
        PassifreqdLabel.setForeground(new java.awt.Color(0, 102, 204));
        PassifreqdLabel.setText("If required *");

        GeneralEditDetailsOkbtn.setBackground(new java.awt.Color(0, 102, 255));
        GeneralEditDetailsOkbtn.setText("Change");
        GeneralEditDetailsOkbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GeneralEditDetailsOkbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneralEditDetailsOkbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout GeneralEditDetailsPanelLayout = new javax.swing.GroupLayout(GeneralEditDetailsPanel);
        GeneralEditDetailsPanel.setLayout(GeneralEditDetailsPanelLayout);
        GeneralEditDetailsPanelLayout.setHorizontalGroup(
            GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralEditDetailsPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralEditDetailsPanelLayout.createSequentialGroup()
                        .addComponent(GeneralEditPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GeneralEditPhoneTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GeneralEditDetailsOkbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneralEditDetailsPanelLayout.createSequentialGroup()
                        .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GeneralEditAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeneralEditAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeneralEditWebAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeneralEditNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneralEditDetailsPanelLayout.createSequentialGroup()
                                .addComponent(GeneralEditNameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                                .addComponent(GeneralEditPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GeneralEditPasswordTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GeneralEditDetailsPanelLayout.createSequentialGroup()
                                .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GeneralEditAccountTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GeneralEditAddressTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GeneralEditWebTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(GeneralEditDetailsPanelLayout.createSequentialGroup()
                        .addComponent(GeneralEditTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PassifreqdLabel)))
                .addGap(192, 192, 192))
        );
        GeneralEditDetailsPanelLayout.setVerticalGroup(
            GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralEditDetailsPanelLayout.createSequentialGroup()
                .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GeneralEditTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassifreqdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GeneralEditPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GeneralEditPasswordTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GeneralEditNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GeneralEditNameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GeneralEditAccountTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneralEditAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeneralEditAddressTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneralEditAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeneralEditWebTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneralEditWebAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(GeneralEditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeneralEditPhoneTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneralEditPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneralEditDetailsOkbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        GeneralBotPanel.add(GeneralEditDetailsPanel, "card4");

        GeneralPaymentPanel.setBackground(new java.awt.Color(34, 36, 49));

        GeneralPaidLabel.setBackground(new java.awt.Color(34, 36, 49));
        GeneralPaidLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GeneralPaidLabel.setForeground(new java.awt.Color(0, 102, 204));
        GeneralPaidLabel.setText("Payments have been done automatically at the time of purchase");
        GeneralPaidLabel.setOpaque(true);

        javax.swing.GroupLayout GeneralPaymentPanelLayout = new javax.swing.GroupLayout(GeneralPaymentPanel);
        GeneralPaymentPanel.setLayout(GeneralPaymentPanelLayout);
        GeneralPaymentPanelLayout.setHorizontalGroup(
            GeneralPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPaymentPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(GeneralPaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        GeneralPaymentPanelLayout.setVerticalGroup(
            GeneralPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralPaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        GeneralBotPanel.add(GeneralPaymentPanel, "card5");

        CorporatePaymentPanel.setBackground(new java.awt.Color(34, 36, 49));

        CorporatePaymentTable.setBackground(new java.awt.Color(204, 255, 255));
        CorporatePaymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CoporatePayment.setViewportView(CorporatePaymentTable);

        PaymentButton.setBackground(new java.awt.Color(255, 0, 51));
        PaymentButton.setText("Pay ");
        PaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CorporatePaymentPanelLayout = new javax.swing.GroupLayout(CorporatePaymentPanel);
        CorporatePaymentPanel.setLayout(CorporatePaymentPanelLayout);
        CorporatePaymentPanelLayout.setHorizontalGroup(
            CorporatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorporatePaymentPanelLayout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(PaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(509, Short.MAX_VALUE))
            .addGroup(CorporatePaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoporatePayment)
                .addContainerGap())
        );
        CorporatePaymentPanelLayout.setVerticalGroup(
            CorporatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorporatePaymentPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(CoporatePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(PaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        GeneralBotPanel.add(CorporatePaymentPanel, "card6");

        MyBookingPanel.setBackground(new java.awt.Color(34, 36, 49));

        BookTable.setBackground(new java.awt.Color(204, 255, 255));
        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Ticket ID", "Concert ID", "Concert Name", "Ticket Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GeneralBookTable.setViewportView(BookTable);
        if (BookTable.getColumnModel().getColumnCount() > 0) {
            BookTable.getColumnModel().getColumn(0).setResizable(false);
            BookTable.getColumnModel().getColumn(1).setResizable(false);
            BookTable.getColumnModel().getColumn(2).setResizable(false);
            BookTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout MyBookingPanelLayout = new javax.swing.GroupLayout(MyBookingPanel);
        MyBookingPanel.setLayout(MyBookingPanelLayout);
        MyBookingPanelLayout.setHorizontalGroup(
            MyBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralBookTable, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
                .addContainerGap())
        );
        MyBookingPanelLayout.setVerticalGroup(
            MyBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyBookingPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(GeneralBookTable, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        GeneralBotPanel.add(MyBookingPanel, "card2");

        CorporateBookingPanel.setBackground(new java.awt.Color(34, 36, 49));

        BookTable1.setBackground(new java.awt.Color(204, 255, 255));
        BookTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BookTableScroll.setViewportView(BookTable1);

        btnBookCorporate.setBackground(new java.awt.Color(255, 0, 0));
        btnBookCorporate.setText("Book ");
        btnBookCorporate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookCorporateActionPerformed(evt);
            }
        });

        CorporateTicketTxtfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CorporateTicketTxtfieldKeyReleased(evt);
            }
        });

        BookcorLabel.setBackground(new java.awt.Color(34, 36, 49));
        BookcorLabel.setForeground(new java.awt.Color(153, 255, 255));
        BookcorLabel.setText("How many tickets you want to purchase?");
        BookcorLabel.setOpaque(true);

        btnBackCorporate.setBackground(new java.awt.Color(255, 0, 0));
        btnBackCorporate.setText("Back");
        btnBackCorporate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCorporateActionPerformed(evt);
            }
        });

        CorporateErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        BandTableCor.setBackground(new java.awt.Color(204, 255, 255));
        BandTableCor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BandTableCorView.setViewportView(BandTableCor);

        javax.swing.GroupLayout CorporateBookingPanelLayout = new javax.swing.GroupLayout(CorporateBookingPanel);
        CorporateBookingPanel.setLayout(CorporateBookingPanelLayout);
        CorporateBookingPanelLayout.setHorizontalGroup(
            CorporateBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorporateBookingPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BandTableCorView, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(BookTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorporateBookingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BookcorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438))
            .addGroup(CorporateBookingPanelLayout.createSequentialGroup()
                .addGroup(CorporateBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CorporateBookingPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnBackCorporate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CorporateBookingPanelLayout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addComponent(btnBookCorporate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CorporateBookingPanelLayout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addGroup(CorporateBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CorporateBookingPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CorporateErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CorporateTicketTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CorporateBookingPanelLayout.setVerticalGroup(
            CorporateBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorporateBookingPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnBackCorporate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(CorporateBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BandTableCorView, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(BookcorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorporateTicketTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorporateErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnBookCorporate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        GeneralBotPanel.add(CorporateBookingPanel, "card2");

        GeneralBookingPanel.setBackground(new java.awt.Color(34, 36, 49));

        BookTable2.setBackground(new java.awt.Color(204, 255, 255));
        BookTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BookTableScroll1.setViewportView(BookTable2);

        BookPremiumRadio.setBackground(new java.awt.Color(34, 36, 49));
        btnGroupCorporate.add(BookPremiumRadio);
        BookPremiumRadio.setForeground(new java.awt.Color(255, 255, 255));
        BookPremiumRadio.setText("Ticket A");

        BookNonPremiumRadio.setBackground(new java.awt.Color(34, 36, 49));
        btnGroupCorporate.add(BookNonPremiumRadio);
        BookNonPremiumRadio.setForeground(new java.awt.Color(255, 255, 255));
        BookNonPremiumRadio.setText("Ticket B");

        btnBookGeneral.setBackground(new java.awt.Color(255, 0, 0));
        btnBookGeneral.setText("Book ");
        btnBookGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookGeneralActionPerformed(evt);
            }
        });

        btnBackGeneral.setBackground(new java.awt.Color(255, 0, 0));
        btnBackGeneral.setText("Back");
        btnBackGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackGeneralActionPerformed(evt);
            }
        });

        BandTable.setBackground(new java.awt.Color(204, 255, 255));
        BandTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BandTableScroll.setViewportView(BandTable);

        GeneralTicketTxtfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GeneralTicketTxtfieldKeyReleased(evt);
            }
        });

        BookcorLabel1.setBackground(new java.awt.Color(34, 36, 49));
        BookcorLabel1.setForeground(new java.awt.Color(153, 255, 255));
        BookcorLabel1.setText("How many tickets you want to purchase?");
        BookcorLabel1.setOpaque(true);

        GeneralErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout GeneralBookingPanelLayout = new javax.swing.GroupLayout(GeneralBookingPanel);
        GeneralBookingPanel.setLayout(GeneralBookingPanelLayout);
        GeneralBookingPanelLayout.setHorizontalGroup(
            GeneralBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralBookingPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BookTableScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                .addGroup(GeneralBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnBackGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(BookPremiumRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(BookNonPremiumRadio))
                    .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(btnBookGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(BookcorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(GeneralErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(GeneralTicketTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(400, Short.MAX_VALUE))
            .addGroup(GeneralBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(BandTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(603, Short.MAX_VALUE)))
        );
        GeneralBookingPanelLayout.setVerticalGroup(
            GeneralBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralBookingPanelLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(btnBackGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(BookTableScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(GeneralBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookPremiumRadio)
                    .addComponent(BookNonPremiumRadio))
                .addGap(63, 63, 63)
                .addComponent(BookcorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeneralTicketTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeneralErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBookGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(GeneralBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GeneralBookingPanelLayout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(BandTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );

        GeneralBotPanel.add(GeneralBookingPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralHomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GeneralBotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GeneralHomePagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeneralBotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //initialization of JDBC variables        
    PreparedStatement ps;
    ResultSet rs;
    Connection con;
    
    //Event handling to edit User login details from the database
    private void GeneralEditLoginDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneralEditLoginDetailsBtnActionPerformed
                
        GeneralViewConcertsLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralMybookingLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralPaymentLabel.setBackground(new java.awt.Color(34,36,49));        
        
        GeneralBotPanel.removeAll();
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();
        GeneralBotPanel.add(GeneralEditDetailsPanel);
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();
        
        //displays the user_data from the database and allows us to edit and update
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String query = "select * from user_info where username=?";
            ps = con.prepareStatement(query);
            ps.setString(1, username);
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                GeneralEditNameTxtbox.setText(rs.getString(3));
                GeneralEditAccountTxtbox.setText(rs.getString(7));
                GeneralEditAddressTxtbox.setText(rs.getString(5));
                GeneralEditWebTxtbox.setText(rs.getString(9));
                GeneralEditPhoneTxtbox.setText(rs.getString(6));
                GeneralEditPasswordTxtbox.setText(rs.getString(2));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Not Connected");
        }
    }//GEN-LAST:event_GeneralEditLoginDetailsBtnActionPerformed

    //Event handling to go to my bookings page and view all the bookins fetched from database in a table
    private void GeneralMybookingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneralMybookingLabelMouseClicked
        
        GeneralMybookingLabel.setBackground(new java.awt.Color(255,255,255));
        GeneralViewConcertsLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralPaymentLabel.setBackground(new java.awt.Color(34,36,49));
        
        GeneralBotPanel.removeAll();
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();
        GeneralBotPanel.add(MyBookingPanel);
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();
        
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String query1 = "select book_info.concert_id, concert_name, booking_id, tickets_bought, total_price from concert_info, book_info where ticket_booker =? AND concert_info.concert_id = book_info.concert_id;";
            ps = con.prepareStatement(query1);
            ps.setString(1, username);
            rs = ps.executeQuery();
            BookTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Not Connected");
        }
        
        
        
    }//GEN-LAST:event_GeneralMybookingLabelMouseClicked
    
    //Event handling to View all the concerts that is currently available throught the database
    private void GeneralViewConcertsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneralViewConcertsLabelMouseClicked
        
        GeneralViewConcertsLabel.setBackground(new java.awt.Color(255,255,255));
        GeneralMybookingLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralPaymentLabel.setBackground(new java.awt.Color(34,36,49));
        
        GeneralBotPanel.removeAll();
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();
        GeneralBotPanel.add(GeneralViewConcertsPanel);
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();        
        
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String sql = "select concert_info.concert_id, concert_name, concert_venue, concert_createdby, sponsor, start_date,end_date,start_time, end_time from concert_info,concert_schedule where concert_info.concert_id = concert_schedule.concert_id;";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ViewTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_GeneralViewConcertsLabelMouseClicked

    //Event handling to View the payment tab for the General and Corporate User and display the pending payments for corporate
    private void GeneralPaymentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneralPaymentLabelMouseClicked

        GeneralPaymentLabel.setBackground(new java.awt.Color(255,255,255));
        GeneralViewConcertsLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralMybookingLabel.setBackground(new java.awt.Color(34,36,49));
        
        if (accountType.equals("General"))
        {    
            GeneralBotPanel.removeAll();
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
            GeneralBotPanel.add(GeneralPaymentPanel);
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
        }
        else if (accountType.equals("Corporate"))
        {
            GeneralBotPanel.removeAll();
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
            GeneralBotPanel.add(CorporatePaymentPanel);
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();   
        
        
        try
        {
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String sql = "select concert_id, ticket_type, tickets_bought, total_price, book_time from book_info where ticket_booker=? and paid_status=0";
            ps = con.prepareStatement(sql);
            ps.setString(1, username);
            rs = ps.executeQuery();
            CorporatePaymentTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            
        
        }      
    }//GEN-LAST:event_GeneralPaymentLabelMouseClicked
    public int id;
    
    //Event handling to view concert_info in order to book
    private void ViewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTableMouseClicked

        if (accountType.equals("General"))
        {    
            GeneralBotPanel.removeAll();
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
            GeneralBotPanel.add(GeneralBookingPanel);
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
            
        
        try
        {
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            
            DefaultTableModel model = (DefaultTableModel)ViewTable.getModel();
            int selectedRowIndex = ViewTable.getSelectedRow();
            id = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
            
            String sql = "SELECT ticketa_price, ticketb_price, ticketc_price from concert_info WHERE concert_id =?;"; 
            String sql1 = "SELECT band_id, top_bands, agent_id from band_info WHERE concert_id =?;";
            ps = con.prepareStatement(sql);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            BookTable2.setModel(DbUtils.resultSetToTableModel(rs));
            
            ps = con.prepareStatement(sql1);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            BandTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }     
        }
        else if (accountType.equals("Corporate"))
        {
            GeneralBotPanel.removeAll();
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
            GeneralBotPanel.add(CorporateBookingPanel);
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();    
            
        try
        {
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            DefaultTableModel model = (DefaultTableModel)ViewTable.getModel();

            int selectedRowIndex = ViewTable.getSelectedRow();

            id = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
            String sql = "SELECT ticketa_price, ticketb_price, ticketc_price from concert_info WHERE concert_id =?;"; 
            String sql1 = "SELECT band_id, top_bands, agent_id from band_info WHERE concert_id =?;";
            ps = con.prepareStatement(sql);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            BookTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
             ps = con.prepareStatement(sql1);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            BandTableCor.setModel(DbUtils.resultSetToTableModel(rs));
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }         
        }      // TODO add your handling code here:

    }//GEN-LAST:event_ViewTableMouseClicked

    
    //Event handling to log out to the Login screen
    private void GeneralLogOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneralLogOutLabelMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_GeneralLogOutLabelMouseClicked

    
    //Event handling to show and edit user_details from the database
    private void GeneralEditDetailsOkbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneralEditDetailsOkbtnMouseClicked
        // TODO add your handling code here:
        try
        {          
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");  
            String query = "update user_info set name=?, creditno=?, address=?, web_address=?, phoneno=?, password=?" + "where username=?";
            ps = con.prepareStatement(query);

            ps.setString(1, GeneralEditNameTxtbox.getText());
            ps.setString(2, GeneralEditAccountTxtbox.getText());
            ps.setString(3, GeneralEditAddressTxtbox.getText());
            ps.setString(4, GeneralEditWebTxtbox.getText());
            ps.setString(5, GeneralEditPhoneTxtbox.getText());
            ps.setString(6, GeneralEditPasswordTxtbox.getText());
            ps.setString(7, username);
            ps.executeUpdate();
            ps.addBatch();

            JOptionPane.showMessageDialog(null, "Data updated successfully");
            
            
        GeneralViewConcertsLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralMybookingLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralPaymentLabel.setBackground(new java.awt.Color(34,36,49));
            
            GeneralBotPanel.removeAll();
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
            GeneralBotPanel.add(BlankPanel);
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Data couldn't be inserted");
            GeneralEditNameTxtbox.requestFocus();
        }
    }//GEN-LAST:event_GeneralEditDetailsOkbtnMouseClicked

    //Event handling to Book tickets by storing booking information in the database for corporate 
    private void btnBookCorporateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookCorporateActionPerformed
        
        String PATTERN="^[0-9]{0,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(CorporateTicketTxtfield.getText());
        if(!match.matches()){
            CorporateErrorLabel.setText("This field should be a number*");
        }
        else{
            CorporateErrorLabel.setText(null); 
        
        
        int noOfTickets;
        int price = 0;
        
        try
        {   
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            noOfTickets = Integer.parseInt(CorporateTicketTxtfield.getText());
            
            
            String query1 = "select * from concert_info where concert_id=?";
            ps = con.prepareStatement(query1);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                price = rs.getInt(7);
            }
            price = noOfTickets*price;
            
            String query = "INSERT INTO book_info(ticket_booker,concert_id, ticket_type, tickets_bought,total_price,paid_status) VALUES(?,?,?,?,?,?);";  
            ps = con.prepareStatement(query);
            ps.setString(1,username);
            ps.setInt(2,id);
            ps.setString(3,"Ticket C");
            ps.setInt(4, noOfTickets);
            ps.setInt(5, price);
            ps.setInt(6,0);
            
            ps.executeUpdate(); 
            ps.addBatch();
            
            JOptionPane.showMessageDialog(null, "Ticket successfully booked");            
            
            GeneralViewConcertsLabel.setBackground(new java.awt.Color(34,36,49));
            GeneralMybookingLabel.setBackground(new java.awt.Color(34,36,49));
            GeneralPaymentLabel.setBackground(new java.awt.Color(34,36,49));
            
            GeneralBotPanel.removeAll();
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
            GeneralBotPanel.add(BlankPanel);
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate(); 
            
        }
        
        catch(Exception e)
        {   
            JOptionPane.showMessageDialog(null, "You have already made a booking for this concert");
            
           
        }}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookCorporateActionPerformed

    //Event handling to Book tickets by storing booking information in the database for General
    private void btnBookGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookGeneralActionPerformed
        
        String PATTERN="^[0-9]{0,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(GeneralTicketTxtfield.getText());
        if(!match.matches()){
            GeneralErrorLabel.setText("This field should be a number*");
        }
        else{
            GeneralErrorLabel.setText(null);
        
        
        
        
        String datatype = null;
        int GennoOfTickets;
        int Genprice= 0;
        try
        { 
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
        if(BookPremiumRadio.isSelected())
        {
            datatype =BookPremiumRadio.getText();
            String query1 = "select * from concert_info where concert_id=?";
            ps = con.prepareStatement(query1);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                Genprice = rs.getInt(5);
            }
        }
        else if(BookNonPremiumRadio.isSelected())
        {
            datatype =BookNonPremiumRadio.getText();
            String query1 = "select * from concert_info where concert_id=?";
            ps = con.prepareStatement(query1);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                Genprice = rs.getInt(6);
            }
        }
            
            
            String query = "INSERT INTO book_info(ticket_booker,concert_id, ticket_type, tickets_bought, total_price,paid_status) VALUES(?,?,?,?,?,?);";  
            
            GennoOfTickets = Integer.parseInt(GeneralTicketTxtfield.getText());
            Genprice = GennoOfTickets*Genprice;
            ps = con.prepareStatement(query);
            ps.setString(1,username);
            ps.setInt(2,id);
            ps.setString(3,datatype);
            ps.setInt(4,GennoOfTickets);
            ps.setInt(5,Genprice);
            ps.setInt(6,1);
            ps.executeUpdate(); 
            ps.addBatch();
            JOptionPane.showMessageDialog(null, "Concert successfully booked.");
            
            
            GeneralViewConcertsLabel.setBackground(new java.awt.Color(34,36,49));
            GeneralMybookingLabel.setBackground(new java.awt.Color(34,36,49));
            GeneralPaymentLabel.setBackground(new java.awt.Color(34,36,49));
            
            GeneralBotPanel.removeAll();
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate();
            GeneralBotPanel.add(BlankPanel);
            GeneralBotPanel.repaint();
            GeneralBotPanel.revalidate(); 
            
        }
        
        catch(Exception e)
        { 
            JOptionPane.showMessageDialog(null, "You have already made a booking for this concert");
 
        } }       // TODO add your handling code here:
    }//GEN-LAST:event_btnBookGeneralActionPerformed

    //Event handling to go back to the View concerts tab
    private void btnBackGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackGeneralActionPerformed
        GeneralPaymentLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralViewConcertsLabel.setBackground(new java.awt.Color(255,255,255));
        GeneralMybookingLabel.setBackground(new java.awt.Color(34,36,49));  
        

        GeneralBotPanel.removeAll();
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();
        GeneralBotPanel.add(GeneralViewConcertsPanel);
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();    // TODO add your handling code here:   
    }//GEN-LAST:event_btnBackGeneralActionPerformed

    //Event handling to go back to View concerts tab
    private void btnBackCorporateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCorporateActionPerformed
        GeneralPaymentLabel.setBackground(new java.awt.Color(34,36,49));
        GeneralViewConcertsLabel.setBackground(new java.awt.Color(255,255,255));
        GeneralMybookingLabel.setBackground(new java.awt.Color(34,36,49));   
        GeneralBotPanel.removeAll();
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();
        GeneralBotPanel.add(GeneralViewConcertsPanel);
        GeneralBotPanel.repaint();
        GeneralBotPanel.revalidate();  // TODO add your handling code here:
    }//GEN-LAST:event_btnBackCorporateActionPerformed

    //Event handling for Price Validation
    private void CorporateTicketTxtfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorporateTicketTxtfieldKeyReleased
        String PATTERN="^[0-9]{0,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(CorporateTicketTxtfield.getText());
        if(!match.matches()){
            CorporateErrorLabel.setText("This field should be a number*");
        }
        else{
            CorporateErrorLabel.setText(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CorporateTicketTxtfieldKeyReleased
    
    //Event handling for Price Validation
    private void GeneralTicketTxtfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GeneralTicketTxtfieldKeyReleased
    String PATTERN="^[0-9]{0,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(GeneralTicketTxtfield.getText());
        if(!match.matches()){
            GeneralErrorLabel.setText("This field should be a number*");
        }
        else{
            GeneralErrorLabel.setText(null);}    // TODO add your handling code here:
    }//GEN-LAST:event_GeneralTicketTxtfieldKeyReleased

   //Event handling to pay for the tickets for 1 month.
    private void PaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentButtonActionPerformed
        
        Date date = new Date(); // this object contains the current date value  


        SimpleDateFormat formatter = new SimpleDateFormat("dd");  
        if (formatter.format(date).equals ("30")||formatter.format(date).equals ("29") ){
            
          try
            {        
            con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");    
            String query = "update book_info set paid_status=? where ticket_booker=?;";
            ps = con.prepareStatement(query);

            ps.setInt(1,1);
            ps.setString(2, username);
            
            ps.executeUpdate();
            ps.addBatch();

            JOptionPane.showMessageDialog(null, "Account successfully paid");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "You already paid");
            GeneralEditNameTxtbox.requestFocus();
        }
            
        }
        else{ 
        JOptionPane.showMessageDialog(null, "It hasn't been end of month yet.");  
            
        }// TODO add your handling code here:
    }//GEN-LAST:event_PaymentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage(username, accountType).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BandTable;
    private javax.swing.JTable BandTableCor;
    private javax.swing.JScrollPane BandTableCorView;
    private javax.swing.JScrollPane BandTableScroll;
    private javax.swing.JPanel BlankPanel;
    private javax.swing.JRadioButton BookNonPremiumRadio;
    private javax.swing.JRadioButton BookPremiumRadio;
    private javax.swing.JTable BookTable;
    private javax.swing.JTable BookTable1;
    private javax.swing.JTable BookTable2;
    private javax.swing.JScrollPane BookTableScroll;
    private javax.swing.JScrollPane BookTableScroll1;
    private javax.swing.JLabel BookcorLabel;
    private javax.swing.JLabel BookcorLabel1;
    private javax.swing.JScrollPane CoporatePayment;
    private javax.swing.JPanel CorporateBookingPanel;
    private javax.swing.JLabel CorporateErrorLabel;
    private javax.swing.JPanel CorporatePaymentPanel;
    private javax.swing.JTable CorporatePaymentTable;
    private javax.swing.JTextField CorporateTicketTxtfield;
    private javax.swing.JScrollPane GeneralBookTable;
    private javax.swing.JPanel GeneralBookingPanel;
    private javax.swing.JPanel GeneralBotPanel;
    private javax.swing.JLabel GeneralEditAccountLabel;
    private javax.swing.JTextField GeneralEditAccountTxtbox;
    private javax.swing.JLabel GeneralEditAddressLabel;
    private javax.swing.JTextField GeneralEditAddressTxtbox;
    private javax.swing.JButton GeneralEditDetailsOkbtn;
    private javax.swing.JPanel GeneralEditDetailsPanel;
    private javax.swing.JButton GeneralEditLoginDetailsBtn;
    private javax.swing.JLabel GeneralEditNameLabel;
    private javax.swing.JTextField GeneralEditNameTxtbox;
    private javax.swing.JLabel GeneralEditPasswordLabel;
    private javax.swing.JTextField GeneralEditPasswordTxtbox;
    private javax.swing.JLabel GeneralEditPhoneNumberLabel;
    private javax.swing.JTextField GeneralEditPhoneTxtbox;
    private javax.swing.JLabel GeneralEditTitleLabel;
    private javax.swing.JLabel GeneralEditWebAdressLabel;
    private javax.swing.JTextField GeneralEditWebTxtbox;
    private javax.swing.JLabel GeneralErrorLabel;
    private javax.swing.JPanel GeneralHomePagePanel;
    private javax.swing.JLabel GeneralLogOutLabel;
    public javax.swing.JLabel GeneralLoginInfoLabel;
    private javax.swing.JLabel GeneralLoginPicLabel;
    private javax.swing.JLabel GeneralMybookingLabel;
    private javax.swing.JLabel GeneralPaidLabel;
    private javax.swing.JLabel GeneralPaymentLabel;
    private javax.swing.JPanel GeneralPaymentPanel;
    private javax.swing.JTextField GeneralTicketTxtfield;
    private javax.swing.JLabel GeneralTitleLabel;
    private javax.swing.JLabel GeneralViewConcertsLabel;
    private javax.swing.JPanel GeneralViewConcertsPanel;
    private javax.swing.JScrollPane GeneralViewTable;
    private javax.swing.JPanel MyBookingPanel;
    private javax.swing.JLabel PassifreqdLabel;
    private javax.swing.JButton PaymentButton;
    private javax.swing.JTable ViewTable;
    private javax.swing.JButton btnBackCorporate;
    private javax.swing.JButton btnBackGeneral;
    private javax.swing.JButton btnBookCorporate;
    private javax.swing.JButton btnBookGeneral;
    private javax.swing.ButtonGroup btnGroupCorporate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblmainicon;
    // End of variables declaration//GEN-END:variables

}

