/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beta;


import javax.swing.*;
import java.sql.*;
import java.util.regex.*;

public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form register2
     */

    public RegisterPage() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccTypBtnGroup = new javax.swing.ButtonGroup();
        RegistrationPnl = new javax.swing.JPanel();
        UsernameLbl = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        PasswordLbl = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        NameLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        EmailLbl = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        AddressLbl = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        PhoneLbl = new javax.swing.JLabel();
        PhoneTxt = new javax.swing.JTextField();
        PhoneText = new javax.swing.JSeparator();
        WebLbl = new javax.swing.JLabel();
        CreditLbl = new javax.swing.JLabel();
        CreditTxt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        AccTypLbl = new javax.swing.JLabel();
        GeneralBtn = new javax.swing.JRadioButton();
        OrganizerBtn = new javax.swing.JRadioButton();
        CorporateBtn = new javax.swing.JRadioButton();
        UsernameIcon = new javax.swing.JLabel();
        PasswordIcon = new javax.swing.JLabel();
        EmailIcon = new javax.swing.JLabel();
        AddressIcon = new javax.swing.JLabel();
        PhoneIcon = new javax.swing.JLabel();
        WebIcon = new javax.swing.JLabel();
        CreditIcon = new javax.swing.JLabel();
        AccountIcon = new javax.swing.JLabel();
        BackToLoginBtn = new javax.swing.JButton();
        RegisterBtn = new javax.swing.JButton();
        MainIcon = new javax.swing.JLabel();
        NameIcon = new javax.swing.JLabel();
        UsernameError = new javax.swing.JLabel();
        PasswordError = new javax.swing.JLabel();
        EmailError = new javax.swing.JLabel();
        NameError = new javax.swing.JLabel();
        AddressError = new javax.swing.JLabel();
        PhoneError = new javax.swing.JLabel();
        WebTxt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistrationPnl.setBackground(new java.awt.Color(34, 36, 49));
        RegistrationPnl.setForeground(new java.awt.Color(255, 255, 255));

        UsernameLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        UsernameLbl.setForeground(new java.awt.Color(0, 102, 204));
        UsernameLbl.setText("Username :");

        UsernameTxt.setBackground(new java.awt.Color(34, 36, 49));
        UsernameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UsernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        UsernameTxt.setBorder(null);
        UsernameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UsernameTxtKeyReleased(evt);
            }
        });

        PasswordLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        PasswordLbl.setForeground(new java.awt.Color(0, 102, 204));
        PasswordLbl.setText("Password :");

        PasswordTxt.setBackground(new java.awt.Color(34, 36, 49));
        PasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTxt.setBorder(null);
        PasswordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordTxtKeyReleased(evt);
            }
        });

        NameLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(0, 102, 204));
        NameLbl.setText("Name :");

        NameTxt.setBackground(new java.awt.Color(34, 36, 49));
        NameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NameTxt.setForeground(new java.awt.Color(255, 255, 255));
        NameTxt.setBorder(null);
        NameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameTxtKeyReleased(evt);
            }
        });

        EmailLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(0, 102, 204));
        EmailLbl.setText("Email :");

        EmailTxt.setBackground(new java.awt.Color(34, 36, 49));
        EmailTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EmailTxt.setForeground(new java.awt.Color(255, 255, 255));
        EmailTxt.setBorder(null);
        EmailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailTxtKeyReleased(evt);
            }
        });

        AddressLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        AddressLbl.setForeground(new java.awt.Color(0, 102, 204));
        AddressLbl.setText("Address :");

        AddressTxt.setBackground(new java.awt.Color(34, 36, 49));
        AddressTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AddressTxt.setForeground(new java.awt.Color(255, 255, 255));
        AddressTxt.setBorder(null);
        AddressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AddressTxtKeyReleased(evt);
            }
        });

        PhoneLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        PhoneLbl.setForeground(new java.awt.Color(0, 102, 204));
        PhoneLbl.setText("PhoneNo :");

        PhoneTxt.setBackground(new java.awt.Color(34, 36, 49));
        PhoneTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PhoneTxt.setForeground(new java.awt.Color(255, 255, 255));
        PhoneTxt.setBorder(null);
        PhoneTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PhoneTxtKeyReleased(evt);
            }
        });

        WebLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        WebLbl.setForeground(new java.awt.Color(0, 102, 204));
        WebLbl.setText("Web Address :");

        CreditLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        CreditLbl.setForeground(new java.awt.Color(0, 102, 204));
        CreditLbl.setText("Credit Card No :");

        CreditTxt.setBackground(new java.awt.Color(34, 36, 49));
        CreditTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CreditTxt.setForeground(new java.awt.Color(255, 255, 255));
        CreditTxt.setBorder(null);

        AccTypLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        AccTypLbl.setForeground(new java.awt.Color(0, 102, 204));
        AccTypLbl.setText("Account Type :");

        AccTypBtnGroup.add(GeneralBtn);
        GeneralBtn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        GeneralBtn.setForeground(new java.awt.Color(0, 102, 204));
        GeneralBtn.setText("General");

        AccTypBtnGroup.add(OrganizerBtn);
        OrganizerBtn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        OrganizerBtn.setForeground(new java.awt.Color(0, 102, 204));
        OrganizerBtn.setText("Organizer");

        AccTypBtnGroup.add(CorporateBtn);
        CorporateBtn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        CorporateBtn.setForeground(new java.awt.Color(0, 102, 204));
        CorporateBtn.setText("Corporate");

        UsernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/username.png"))); // NOI18N

        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/password.png"))); // NOI18N

        EmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/email.jpg"))); // NOI18N

        AddressIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/address.png"))); // NOI18N

        PhoneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/phone.png"))); // NOI18N

        WebIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/web.png"))); // NOI18N

        CreditIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/credit.jpg"))); // NOI18N

        AccountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/account.jpg"))); // NOI18N

        BackToLoginBtn.setBackground(new java.awt.Color(255, 25, 0));
        BackToLoginBtn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        BackToLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackToLoginBtn.setText("Back");
        BackToLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackToLoginBtnMouseClicked(evt);
            }
        });

        RegisterBtn.setBackground(new java.awt.Color(255, 25, 0));
        RegisterBtn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        RegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setText("Create");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        MainIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/gm.png"))); // NOI18N

        NameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/Icons/name.png"))); // NOI18N

        UsernameError.setForeground(new java.awt.Color(255, 0, 51));

        PasswordError.setForeground(new java.awt.Color(255, 0, 51));

        EmailError.setForeground(new java.awt.Color(255, 0, 51));

        NameError.setForeground(new java.awt.Color(255, 0, 51));

        AddressError.setForeground(new java.awt.Color(255, 0, 51));

        PhoneError.setForeground(new java.awt.Color(255, 0, 51));

        WebTxt.setBackground(new java.awt.Color(34, 36, 49));
        WebTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        WebTxt.setForeground(new java.awt.Color(255, 255, 255));
        WebTxt.setBorder(null);

        jLabel1.setBackground(new java.awt.Color(34, 36, 49));
        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("Optional");

        javax.swing.GroupLayout RegistrationPnlLayout = new javax.swing.GroupLayout(RegistrationPnl);
        RegistrationPnl.setLayout(RegistrationPnlLayout);
        RegistrationPnlLayout.setHorizontalGroup(
            RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(UsernameIcon)
                        .addComponent(AddressIcon))
                    .addComponent(WebIcon)
                    .addComponent(NameIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressLbl)
                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLbl)
                            .addComponent(UsernameLbl)
                            .addComponent(WebLbl))
                        .addGap(10, 10, 10)
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddressTxt)
                                    .addComponent(jSeparator5)
                                    .addComponent(NameTxt)
                                    .addComponent(jSeparator3)
                                    .addComponent(UsernameTxt)
                                    .addComponent(jSeparator1)
                                    .addComponent(UsernameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WebTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                        .addGap(215, 215, 215)
                                        .addComponent(PasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                                    .addGap(69, 69, 69)
                                                    .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(PasswordIcon)
                                                        .addComponent(EmailIcon)
                                                        .addComponent(PhoneIcon)
                                                        .addComponent(CreditIcon))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                                            .addComponent(PhoneLbl)
                                                            .addGap(58, 58, 58)
                                                            .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(EmailLbl)
                                                        .addComponent(PasswordLbl)
                                                        .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                                            .addComponent(CreditLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(CreditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                                    .addGap(215, 215, 215)
                                                    .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                                    .addGap(215, 215, 215)
                                                    .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(EmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PhoneError, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))))
                            .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressError, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(BackToLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                                    .addComponent(GeneralBtn)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(OrganizerBtn)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(CorporateBtn)
                                                    .addGap(11, 11, 11))))
                                        .addGap(42, 42, 42)
                                        .addComponent(RegisterBtn))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(54, 54, 54))
            .addGroup(RegistrationPnlLayout.createSequentialGroup()
                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AccountIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccTypLbl))
                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(MainIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistrationPnlLayout.setVerticalGroup(
            RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UsernameLbl)
                        .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UsernameIcon)
                    .addComponent(PasswordIcon)
                    .addComponent(PasswordLbl)
                    .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UsernameError)
                            .addComponent(PasswordError))
                        .addGap(20, 20, 20)
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NameLbl)
                                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmailLbl)
                                .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EmailIcon)))
                    .addComponent(NameIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailError)
                    .addComponent(NameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPnlLayout.createSequentialGroup()
                                .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPnlLayout.createSequentialGroup()
                                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddressLbl)
                                        .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddressIcon))
                                    .addComponent(PhoneIcon))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(AddressError)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WebLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPnlLayout.createSequentialGroup()
                                        .addComponent(WebTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(PhoneError)
                                .addGap(18, 18, 18)
                                .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(CreditIcon))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPnlLayout.createSequentialGroup()
                                        .addComponent(CreditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CreditLbl, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WebIcon)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountIcon)
                            .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AccTypLbl)
                                .addComponent(GeneralBtn)
                                .addComponent(OrganizerBtn)
                                .addComponent(CorporateBtn)))
                        .addGap(57, 57, 57)
                        .addGroup(RegistrationPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterBtn)
                            .addComponent(BackToLoginBtn))
                        .addGap(58, 58, 58))
                    .addGroup(RegistrationPnlLayout.createSequentialGroup()
                        .addComponent(PhoneLbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrationPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrationPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //initializing variables for JDBC connection and execution
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    //Event handling in register page to go back to the login page
    private void BackToLoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToLoginBtnMouseClicked

        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackToLoginBtnMouseClicked
    
    //Event handling to register your details to the database and go to the login screen
    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        
        
        String PATTERN1 = "^[0-9]{0,20}$"; //validation pattern of phone number in RegisterPage
        Pattern patt1 = Pattern.compile(PATTERN1);
        Matcher match1 = patt1.matcher(PhoneTxt.getText());
        if(!match1.matches()){
            PhoneError.setText("Phone no incorrect!");
        }
        else{
            PhoneError.setText(null);
            
            String PATTERN2 = "^[a-zA-Z0-9]{1,30}@[a-zA-Z0-9]{1,15}[.][a-zA-Z0-9]{1,15}$"; //validation pattern of enmail address in RegisterPage
        Pattern pat2 = Pattern.compile(PATTERN2);
        Matcher match2 = pat2.matcher(EmailTxt.getText());
        if(!match2.matches()){
            EmailError.setText("Email incorrect!");
        }
        else{
            EmailError.setText(null);
        

        String type = null;
        // Choose account type during registration
        if(GeneralBtn.isSelected())
        {
            type = GeneralBtn.getText();
        }
        else if(CorporateBtn.isSelected())
        {
            type = CorporateBtn.getText();
        }
        else if(OrganizerBtn.isSelected())
        {
            type = OrganizerBtn.getText();
        }
        // Establish a connection with database and execute queries in order to register to get access to the HomePages
        try
        {   con = DriverManager.getConnection("jdbc:mysql://localhost/musicfestival","root","");
            String query = "insert into user_info(username,password,name,email,address,phoneno,creditno,account_type,web_address)" + "values(?,?,?,?,?,?,?,?,?)";
            String query2= "select username from user_info where username=?";

            ps = con.prepareStatement(query2);
            ps.setString(1, UsernameTxt.getText());
            rs = ps.executeQuery();
            if(!rs.next())
            {
                if(UsernameTxt.getText().equals("") || PasswordTxt.getText().equals("") || NameTxt.getText().equals("") || EmailTxt.getText().equals("") || AddressTxt.getText().equals("") || CreditTxt.getText().equals("") || WebTxt.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, "Please fill in all the data");
                }
                else
                {
                    ps = con.prepareStatement(query);

                    ps.setString(1, UsernameTxt.getText());
                    ps.setString(2, PasswordTxt.getText());
                    ps.setString(3, NameTxt.getText());
                    ps.setString(4, EmailTxt.getText());
                    ps.setString(5, AddressTxt.getText());
                    ps.setString(6, PhoneTxt.getText());
                    ps.setString(7, CreditTxt.getText());
                    ps.setString(8, type);
                    ps.setString(9, WebTxt.getText());
                    ps.executeUpdate();
                    ps.addBatch();

                    JOptionPane.showMessageDialog(null, "Registration successfull");

                    LoginForm lgf = new LoginForm();
                    lgf.setVisible(true);
                    lgf.pack();
                    lgf.setLocationRelativeTo(null);
                    lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Username already exits");
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Unable to Register");
            UsernameTxt.requestFocus();
        }}}
    }//GEN-LAST:event_RegisterBtnActionPerformed
    
    //Event Handling for username validation
    private void UsernameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameTxtKeyReleased
        
        String PATTERN = "^[a-zA-Z0-9]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(UsernameTxt.getText());
        
        if(!match.matches()){
            UsernameError.setText("Username incorrect!");
        }
        else{
            UsernameError.setText(null);
        }
    }//GEN-LAST:event_UsernameTxtKeyReleased
   //Event Handling for password validation
    private void PasswordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTxtKeyReleased
        //^.*(?=.{8,})(?=..*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$
        String PATTERN = "^[a-zA-Z0-9$%,><.?/@!]{5,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PasswordTxt.getText());
        
        if(!match.matches()){
            PasswordError.setText("Enter at least 5 characters!");
        }
        else{
            PasswordError.setText(null);
        }
    }//GEN-LAST:event_PasswordTxtKeyReleased
   //Event Handling for Name validation
    private void NameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTxtKeyReleased
        
        String PATTERN = "^[a-zA-Z]{0,50}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(NameTxt.getText());
        if(!match.matches()){
            NameError.setText("Name incorrect!");
        }
        else{
            NameError.setText(null);
        }
    }//GEN-LAST:event_NameTxtKeyReleased
    //Event Handling for Email validation
    private void EmailTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailTxtKeyReleased
        
        String PATTERN = "^[a-zA-Z0-9]{1,30}@[a-zA-Z0-9]{1,15}[.][a-zA-Z0-9]{1,15}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(EmailTxt.getText());
        if(!match.matches()){
            EmailError.setText("Email incorrect!");
        }
        else{
            EmailError.setText(null);
        }
    }//GEN-LAST:event_EmailTxtKeyReleased
    //Event Handling for Phone no. validation
    private void PhoneTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneTxtKeyReleased
        
        String PATTERN = "^[0-9]{0,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PhoneTxt.getText());
        if(!match.matches()){
            PhoneError.setText("Phone no incorrect!");
        }
        else{
            PhoneError.setText(null);
        }
    }//GEN-LAST:event_PhoneTxtKeyReleased
    //Event Handling for Address validation
    private void AddressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddressTxtKeyReleased
        
        String PATTERN = "^[a-zA-Z0-9,]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(AddressTxt.getText());
        if(!match.matches()){
            AddressError.setText("Enter Valid Address!");
        }
        else{
            AddressError.setText(null);
        }
    }//GEN-LAST:event_AddressTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AccTypBtnGroup;
    private javax.swing.JLabel AccTypLbl;
    private javax.swing.JLabel AccountIcon;
    private javax.swing.JLabel AddressError;
    private javax.swing.JLabel AddressIcon;
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JButton BackToLoginBtn;
    private javax.swing.JRadioButton CorporateBtn;
    private javax.swing.JLabel CreditIcon;
    private javax.swing.JLabel CreditLbl;
    private javax.swing.JTextField CreditTxt;
    private javax.swing.JLabel EmailError;
    private javax.swing.JLabel EmailIcon;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JRadioButton GeneralBtn;
    private javax.swing.JLabel MainIcon;
    private javax.swing.JLabel NameError;
    private javax.swing.JLabel NameIcon;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JRadioButton OrganizerBtn;
    private javax.swing.JLabel PasswordError;
    private javax.swing.JLabel PasswordIcon;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JLabel PhoneError;
    private javax.swing.JLabel PhoneIcon;
    private javax.swing.JLabel PhoneLbl;
    private javax.swing.JSeparator PhoneText;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JPanel RegistrationPnl;
    private javax.swing.JLabel UsernameError;
    private javax.swing.JLabel UsernameIcon;
    private javax.swing.JLabel UsernameLbl;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JLabel WebIcon;
    private javax.swing.JLabel WebLbl;
    private javax.swing.JTextField WebTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
